spring:
  main:
    web-application-type: none
  threads:
    virtual:
      enabled: true

trap:
  download:
    trap-types:
      - singles
      - doubles
      - handicap
      - skeet
      - clays
      - fivestand
      - doublesskeet
    file-ids:
      singles: 77009b20-98d6-4a72-978f-b9a7915d6f67
      doubles: 93e760dc-5eb3-4dc8-99b0-888940fa6cc2
      handicap: 1b7b0a6b-9bc9-4961-9682-3456a1cb4639
      skeet: 493ddc58-a891-4614-999f-3947d14afd76
      clays: 43eaa17c-abf7-4cc7-81eb-4a8885b6e6d6
      fivestand: a84359f2-b915-4abe-b967-2cc4294b42eb
      doublesskeet: 4f209d11-17eb-49cf-b279-fc1f5ac3217a
  report:
    output-file-prefix: league-data-
    output-file-pattern: yyyyMMddHHmmss
    season-cutoff-month: 8
  http:
    connect-timeout: 5s
    read-timeout: 2m
