app:
  mariaDB4j:
    databaseName: ${random.uuid}
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
