name: Main Branch

on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 25 ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Setup and execute Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Run Gradle build
        env:
          SPRING_PROFILES_ACTIVE: test 
        run: ./gradlew build --parallel --configuration-cache

      - name: Generate file
        run: |
          cd build/libs/
          ls -ltra
          mv trap-*.jar trap.jar
          java -jar trap.jar

      - name: Test file exists
        run: |
          cd build/libs/
          test -f league-data-*.xlsx || exit 1

      - name: Test file was generated properly
        run: |
          cd build/libs/
          file1size=$(stat -c %s league-data-*.xlsx)
          echo "file 1 size successful"
          file2size=$(stat -c %s ../../src/main/resources/main-template.xlsx)
          echo "file 2 size successful"
          echo "file1size"
          echo $file1size
          echo "file2size"
          echo $file2size
          if [ "$file1size" -lt "$file2size" ]; then
            echo "file 1 is smaller"
            exit 1
          fi
