name: Main Branch

on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17, 20 ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - name: Setup and execute Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run Gradle build
        shell: bash
        run: >-
          export SPRING_PROFILES_ACTIVE=test && ./gradlew build --no-daemon --info
      - name: Generate file
        run: |
          cd build/libs/
          mv trap-*.jar trap.jar
          java -jar trap.jar
          ls -ltra
          test -f league-data-*.xlsx || exit 1
          file1size=$(stat -c %s league-data-*.xlsx)
          echo "file 1 size successful"
          file2size=$(stat -c %s ../../src/main/resources/main-template.xlsx)
          echo "file 2 size successful"
          echo "file1size"
          echo $file1size
          echo "file2size"
          echo $file2size
          if [ "$file1size" -lt "$file2size" ]; then
            echo "file 1 is smaller"
            exit 1
          fi
