name: Main Branch

on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17, 20 ]

    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - name: Setup and execute Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run Gradle task
        shell: bash
        run: >-
          ./gradlew build -x test --no-daemon --info
      - name: Generate file
        run: |
          ls -ltra
          cd build/libs/
          ls -ltra
          java -jar trap-5.1.0.jar
          ls -ltra

