name: Main Branch

on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17, 20 ]

    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - name: Setup and execute Gradle
        uses: gradle/gradle-build-action@v2.1.5
      - name: Run Gradle task
        shell: bash
        run: >-
          ./gradlew build --no-daemon --info
          -Dorg.gradle.parallel=true
          -Dorg.gradle.caching=true
          -Dorg.gradle.jvmargs="-Xms4g -Xmx6g -XX:+HeapDumpOnOutOfMemoryError -XX:MaxMetaspaceSize=512m"
#       - name: Set Swap Space
#         uses: pierotofy/set-swap-space@master
#         with:
#           swap-size-gb: 10
#       - name: Build and analyze
#         shell: bash
#         run: >-
#           ./gradlew build --no-daemon --info
#           -Dorg.gradle.jvmargs="-Xms4g -Xmx6g -XX:+HeapDumpOnOutOfMemoryError -XX:MaxMetaspaceSize=512m"
#           -Dkotlin.daemon.jvm.options="-Xmx1g"
