name: Main Branch

on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17, 20 ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - name: Setup and execute Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run Gradle build
        shell: bash
        run: >-
          export SPRING_PROFILES_ACTIVE=test && ./gradlew build --no-daemon --info
      - name: Generate file
        shell: bash
        run: |
          cd build/libs/
          mv trap-*.jar trap.jar
          java -jar trap.jar
          ls -ltra
          test -f league-data-*.xls || exit 1

