name: Main Branch

on:
  push:
  
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2g"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17, 20 ]

    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Build and analyze
        run: ./gradlew build --no-daemon --info
