name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.12
      uses: actions/setup-java@v1
      with:
        java-version: 1.12
    - name: Grant rights
      run: chmod 0755 gradlew && git add gradlew
    - name: Build with Gradle
      run: ./gradlew build
